package ticket

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// GetTicketURL generates an URL for the get ticket operation
type GetTicketURL struct {
	CarSize string
	LotID   int64

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTicketURL) WithBasePath(bp string) *GetTicketURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetTicketURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetTicketURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/ticket/getTicket/lot/{lotId}/carSize/{carSize}"

	carSize := o.CarSize
	if carSize != "" {
		_path = strings.Replace(_path, "{carSize}", carSize, -1)
	} else {
		return nil, errors.New("CarSize is required on GetTicketURL")
	}
	lotID := swag.FormatInt64(o.LotID)
	if lotID != "" {
		_path = strings.Replace(_path, "{lotId}", lotID, -1)
	} else {
		return nil, errors.New("LotID is required on GetTicketURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetTicketURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetTicketURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetTicketURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetTicketURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetTicketURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetTicketURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
